language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - npm run ci && npm run build

  jobs:
  include:
    - stage: npm release
      if: branch = master
      node_js: "8"
      script: npm run semantic-release && npm run deploy-storybook